---
services:
  pg14:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "54314:5432"
    container_name: pg14
    volumes:
      - ./volumes/pg14/data:/var/lib/postgresql/data
  redis6:
    image: redis:6
    ports:
      - "6379:6379"
    container_name: redis6
  mysql57:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3307:3306"
    container_name: mysql57
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    command:
      - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --max-allowed-packet=128M
    volumes:
      - ./volumes/mysql57/data:/var/lib/mysql
  es8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    ports:
      - 9208:9200
    container_name: es8
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    command: ["bash", "-c", "bin/elasticsearch-plugin install analysis-kuromoji analysis-icu; docker-entrypoint.sh"]
